"""
services/referral.py

Referral network mapper — pure SQL, no LLM.
Tracks where bookings originate: client referrals, vendors, direct, social, etc.
"""

from typing import Optional

from core.database import get_db


def get_referral_sources() -> list[dict]:
    """
    Aggregate bookings.source — count and total revenue per source.
    """
    with get_db() as conn:
        rows = conn.execute(
            """
            SELECT
                COALESCE(source, 'unknown') AS source,
                COUNT(*) AS booking_count,
                SUM(CASE WHEN balance_paid = TRUE THEN 1 ELSE 0 END) AS paid_count,
                COALESCE(SUM(CASE WHEN balance_paid = TRUE THEN amount ELSE 0 END), 0) AS total_revenue,
                COALESCE(AVG(CASE WHEN balance_paid = TRUE THEN amount END), 0) AS avg_booking_value
            FROM bookings
            GROUP BY source
            ORDER BY total_revenue DESC
            """
        ).fetchall()
    return [dict(r) for r in rows]


def get_top_referring_clients(limit: int = 10) -> list[dict]:
    """
    Clients who referred other clients (via clients.referred_by field).
    Returns referring client's name, number of referrals, and total revenue
    generated by referred clients.
    """
    with get_db() as conn:
        rows = conn.execute(
            """
            SELECT
                ref.id              AS referring_client_id,
                ref.name            AS referring_client_name,
                ref.email           AS referring_client_email,
                COUNT(c.id)         AS referrals_count,
                COALESCE(SUM(b.amount), 0) AS referred_revenue
            FROM clients ref
            JOIN clients c ON c.referred_by = ref.id
            LEFT JOIN bookings b ON b.client_id = c.id AND b.balance_paid = TRUE
            GROUP BY ref.id
            ORDER BY referred_revenue DESC
            LIMIT ?
            """,
            (limit,),
        ).fetchall()
    return [dict(r) for r in rows]


def get_vendor_referrals() -> list[dict]:
    """
    All vendors with their referrals_sent and referrals_received counts.
    Also includes bookings where source_detail matches the vendor name.
    """
    with get_db() as conn:
        rows = conn.execute(
            """
            SELECT
                v.id,
                v.name,
                v.type,
                v.contact_name,
                v.email,
                v.phone,
                v.referrals_sent,
                v.referrals_received,
                COUNT(b.id) AS bookings_attributed,
                COALESCE(SUM(CASE WHEN b.balance_paid = TRUE THEN b.amount ELSE 0 END), 0) AS revenue_attributed
            FROM vendors v
            LEFT JOIN bookings b ON (
                b.source = 'vendor'
                AND b.source_detail = v.name
            )
            GROUP BY v.id
            ORDER BY v.referrals_sent DESC, revenue_attributed DESC
            """
        ).fetchall()
    return [dict(r) for r in rows]


def add_vendor(
    name: str,
    type: str,
    contact_name: Optional[str] = None,
    email: Optional[str] = None,
    phone: Optional[str] = None,
) -> dict:
    """
    Add a new vendor to the vendors table.
    Returns the created vendor record.
    """
    with get_db() as conn:
        cur = conn.execute(
            """
            INSERT INTO vendors (name, type, contact_name, email, phone)
            VALUES (?, ?, ?, ?, ?)
            """,
            (name, type, contact_name, email, phone),
        )
        vendor_id = cur.lastrowid
        row = conn.execute(
            "SELECT * FROM vendors WHERE id = ?", (vendor_id,)
        ).fetchone()
    return dict(row)


def log_referral(
    booking_id: int,
    source_type: str,
    source_id: Optional[str] = None,
) -> dict:
    """
    Record a referral on a booking by updating its source and source_detail.
    source_type: e.g. 'client', 'vendor', 'instagram', 'google', etc.
    source_id: vendor name or client id as string (optional).
    """
    with get_db() as conn:
        conn.execute(
            "UPDATE bookings SET source = ?, source_detail = ? WHERE id = ?",
            (source_type, source_id, booking_id),
        )
        row = conn.execute(
            "SELECT * FROM bookings WHERE id = ?", (booking_id,)
        ).fetchone()
    if not row:
        return {"error": f"Booking {booking_id} not found"}
    return dict(row)


def get_referral_summary() -> dict:
    """
    High-level referral summary:
    - Best source by revenue
    - % of bookings from referrals (client or vendor) vs cold/other
    - Total referral revenue
    """
    sources = get_referral_sources()
    top_clients = get_top_referring_clients(limit=5)

    total_revenue = sum(s["total_revenue"] for s in sources)
    total_bookings = sum(s["booking_count"] for s in sources)

    referral_sources = {"client", "vendor", "referral", "word_of_mouth", "wom"}
    referral_bookings = sum(
        s["booking_count"] for s in sources
        if s["source"].lower() in referral_sources
    )
    referral_revenue = sum(
        s["total_revenue"] for s in sources
        if s["source"].lower() in referral_sources
    )

    best_source = sources[0] if sources else None

    pct_referral_bookings = (
        round(referral_bookings / total_bookings * 100, 1)
        if total_bookings > 0 else 0
    )
    pct_referral_revenue = (
        round(referral_revenue / total_revenue * 100, 1)
        if total_revenue > 0 else 0
    )

    return {
        "best_source": best_source,
        "pct_bookings_from_referrals": pct_referral_bookings,
        "pct_revenue_from_referrals": pct_referral_revenue,
        "total_referral_revenue": round(referral_revenue, 2),
        "total_revenue": round(total_revenue, 2),
        "total_bookings": total_bookings,
        "top_referring_clients": top_clients,
        "all_sources": sources,
    }
